---
abstract: 'Bindings to NameTag library'
author:
  - 'Milan Straka <straka@ufal.mff.cuni.cz>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ufal-NameTag
provides:
  Ufal::NameTag:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::Forms:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::NamedEntities:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::NamedEntity:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::Ner:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::TokenRange:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::TokenRanges:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::Tokenizer:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTag::Version:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
  Ufal::NameTagc:
    file: lib/Ufal/NameTag.pm
    version: v1.0.0.1
resources:
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
version: v1.0.0.1
